version: '3.9'
services:
  db:
    image: postgres:15
    container_name: crm_postgres
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: crm_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crm_db
      SPRING_DATASOURCE_USERNAME: crm_user
      SPRING_DATASOURCE_PASSWORD: crm_pass

volumes:
  postgres_data: